LOCAL_PATH := $(call my-dir)
include $(CLEAR_AUTOTOOLS_VARS)
LOCAL_MODULE := binutils
LOCAL_CONFIGURE_DISABLE := nls
LOCAL_CONFIGURE_SHARED := false
LOCAL_CONFIGURE_STATIC := true
LOCAL_CONFIGURE_EXCLUDE_DEFINE := HAVE_MALLOC_H
LOCAL_CFLAGS :=-Wno-error=pointer-sign
include $(BUILD_AUTOTOOLS)
