
include $(CLEAR_AUTOTOOLS_VARS)
LOCAL_MODULE := ffmpeg
LOCAL_LDFLAGS := -Wl,--no-warn-shared-textrel
LOCAL_CONFIGURE_ENABLE := cross-compile gpl runtime-cpudetect indev=alsa
LOCAL_CONFIGURE_SHARED := false
LOCAL_CONFIGURE_STATIC := true
LOCAL_CONFIGURE_DISABLE := libvpx
LOCAL_CONFIGURE_ADDITIONAL_ARGUMENTS := --arch=arm --target-os=linux --cross-prefix=$(shell basename $(TARGET_TOOLS_PREFIX))
LOCAL_CONFIGURE_NO_TARGET := true
LOCAL_CONFIGURE_NO_HOST := true
LOCAL_CONFIGURE_NO_BUILD := true
LOCAL_CONFIGURE_NO_LIBEXECDIR := true
LOCAL_CONFIGURE_EXCLUDE_DEFINE := ARCH_ARM HAVE_MALLOC_H HAVE_PTHREADS
include $(BUILD_AUTOTOOLS)
